# SheepQuest plugin configuration file (config.yml) For settings explanation check this page: https://github.com/Cubixor/SheepQuest/wiki/Config-explanation
#
# Read all comments carefully to do not break plugin
#
# You can use /sq reload command to reload modified files without restarting server.



# Plugin messages language.
# Available languages are:
# en - English
# zh - Chinese
#
# If you have translated the plugin and you would like me to add your translation here, let me know on my discord server:
# http://discord.gg/AQhUVfm
language: en

# NOT READY YET!
#
#database:
#  enabled: true
#  host: "localhost"
#  port: 3306
#  username: "root"
#  password: 12345
#  database: "sheepquest"


# Countdown time.
# Countdown will start when the arena minimum players count will be reached. [seconds]
waiting-time: 40

# Countdown time, when game is full and players can no longer join it. [seconds]
full-waiting-time: 15

# Game time [seconds]
game-time: 360

# Every this amount of time the sheep will appear [seconds]
sheep-time: 10

# Time that will game ending take [seconds]
ending-time: 12

# Player will respawn after this amount of time [seconds]
respawn-time: 7

# Should game use private game chat?
# PLayer messages will be send only to players in the same arena if true. [true/false]
game-chat: true

# Should players be able to choose teams?
# If true, players will be able to choose their team by menu.
# If false, players' team will be chosen randomly. [true/false]
allow-team-choosing: true

# Speed of the sheep [floating point number]
sheep-speed: 0.6

# If true, when the arena ends players will be teleported to main lobby location.
# If false player will be teleported to the place where he was before he joined the arena. [true/false]
use-main-lobby: true

# If true, player will be teleported to the next arena after the previous ends.
# If false, player will be teleported to main lobby or previous location, depending on "use-main-lobby" is set to true or false. [true/false]
auto-join-on-end: true

# Item types and slots.
# Type: item type. Full item list on https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html [item name]
# Slot: slot number. Available slot numbers are 0-8.
items:
  team-choose-item:
    type: CHEST
    slot: 0
  leave-item:
    type: RED_BED
    slot: 8
  weapon-item:
    type: IRON_SWORD
    slot: 0
  sheep-item:
    type: SADDLE
    slot: 1

# All particles that occur in game. Full sound list available here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html [sound]
sounds:
  join: ENTITY_ENDERMAN_TELEPORT
  leave: ENTITY_ENDERMAN_TELEPORT
  team-choose: UI_BUTTON_CLICK
  countdown: BLOCK_NOTE_BLOCK_PLING
  start: ENTITY_ENDERDRAGON_AMBIENT
  sheep-pick: ENTITY_HORSE_SADDLE
  sheep-drop: ITEM_ARMOR_EQUIP_LEATHER
  sheep-bring: ENTITY_PLAYER_LEVELUP
  sheep-spawn: ENTITY_CHICKEN_EGG
  death: BLOCK_ANVIL_LAND
  kill: ENTITY_ELDER_GUARDIAN_CURSE
  respawn-countdown: ENTITY_EXPERIENCE_ORB_PICKUP
  respawn: ENTITY_ENDERMAN_TELEPORT
  ending-countdown: BLOCK_NOTE_BLOCK_HAT
  win: ENTITY_ENDER_DRAGON_DEATH
  defeat: ENTITY_WITHER_SPAWN

# All particles that appear in game. Full particle list available here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html [particle]
particles:
  join: CLOUD
  leave: CLOUD
  sheep-bring: VILLAGER_HAPPY
  sheep-spawn: SPELL_WITCH
  death: END_ROD
  respawn: CLOUD
  win: HEART

  # WARNING! You can't change blood particles, there is only an option to enable or disable it. [true/false]
  enable-blood: true

# If true, blocks behind signs will be changed depending on game state.
color-signs: true
# Full item list on https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html [item name]
sign-colors:
  inactive: BLACK_STAINED_GLASS
  waiting: LIME_STAINED_GLASS
  starting: CYAN_STAINED_GLASS
  ingame: RED_STAINED_GLASS
  ending: PURPLE_STAINED_GLASS

# Configure which commands will be available in game and put them in the command-blocker-list section below.
# Set to WHITELIST to allow players to use only commands from command-blocker-list section.
# Set to BLACKLIST to allow players to use all commands except these from command-blocker-list section. [BLACKLIST/WHITELIST]
command-blocker: BLACKLIST

# List of all commands allowed/blocked in game (without "/").
# You can leave this list empty to block or allow to use all commands. [command name]
command-blocker-list:
  - me
  - spawn

# List of vip-arenas.
# Only players with permission "sheepquest.vip" can join them!
# If you don't want to use this feature just leave it empty. (arena name)
vip-arenas:
  - test

# If true, when the game ends for each player (depends on which place player took) will be executed right command. [true/false]
win-rewards: true

# Rewards list.
# If you don't want to execute commands for some place leave it blank.
# You can use "%player%" placeholder - it will be changed to player name.
# Section 1 is for first place, 2 for second etc. [command]
rewards:
  1:
    - eco give %player% 100
  2:
    - eco give %player% 50
  3:
    - eco give %player% 25
  4:
    - eco give %player% 0

# All special game events' settings
special-events:

  # Should special game events be enabled? [true/false]
  enabled: true

  # How often should special game event perform?
  # For example if set to 40-60, special game event will perform every random amount of time between 40 to 60 seconds. [minSeconds-maxSeconds]
  rate: 40-60

  # Bonus sheep settings
  bonus-sheep:

    # Should it be enabled? [true/false]
    enabled: true

    # Bonus sheep color. List of colors: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/DyeColor.html [color]
    color: PURPLE

    # Bonus sheep speed. [floating point number]
    speed: 1.0

    # Bonus sheep points
    points: 3

    # Bonus sheep particles
    particles:
      spawn: EXPLOSION_HUGE
      bring: DRAGON_BREATH
      carrying: FLAME

    # Bonus sheep sounds
    sounds:
      spawn: ENTITY_GENERIC_EXPLODE
      bring: ENTITY_PLAYER_LEVELUP


# Config version - DO NOT CHANGE IT!
config-version: 1.3