name: SheepQuest
version: 1.4
main: me.cubixor.sheepquest.SheepQuest
authors: [Cubixor]
softdepend: [Vault, Multiverse-Core]
api-version: 1.13
description: SheepQuest minigame plugin.
commands:
  sheepquest:
    description: Main plugin command
    aliases: sq
    usage: /sheepquest
  t:
    description: Team chat in game
    usage: /t
permissions:
  sheepquest.*:
    default: op
    description: Gives access to all plugin commands.
    children:
      sheepquest.setup.*: true
      sheepquest.play.*: true
      sheepquest.staff.*: true
      sheepquest.bypass: true
      sheepquest.vip: true


  sheepquest.setup.*:
    default: op
    description: Gives access to use arena setup commands.
    children:
      sheepquest.setup.check: true
      sheepquest.setup.create: true
      sheepquest.setup.delete: true
      sheepquest.setup.setmainlobby: true
      sheepquest.setup.setwaitinglobby: true
      sheepquest.setup.setminplayers: true
      sheepquest.setup.setmaxplayers: true
      sheepquest.setup.wand: true
      sheepquest.setup.setsheepspawn: true
      sheepquest.setup.setspawn: true
      sheepquest.setup.setteamarea: true
      sheepquest.setup.signs: true
      sheepquest.setup.reload: true
      sheepquest.setup.help: true
      sheepquest.setup.menu: true

  speepquest.setup.check:
    default: op
    description: Gives access to /sq check command.
  speepquest.setup.create:
    default: op
    description: Gives access to /sq create command.
  speepquest.setup.delete:
    default: op
    description: Gives access to /sq delete command.
  speepquest.setup.setmainlobby:
    default: op
    description: Gives access to /sq setmainlobby command.
  speepquest.setup.setwaitinglobby:
    default: op
    description: Gives access to /sq setwaitinglobby command.
  speepquest.setup.setminplayers:
    default: op
    description: Gives access to /sq setminplayers command.
  speepquest.setup.setmaxplayers:
    default: op
    description: Gives access to /sq setmaxplayers command.
  speepquest.setup.wand:
    default: op
    description: Gives access to /sq wand command.
  speepquest.setup.setsheepspawn:
    default: op
    description: Gives access to /sq setsheepspawn command.
  speepquest.setup.setspawn:
    default: op
    description: Gives access to /sq setspawn command.
  speepquest.setup.setteamarea:
    default: op
    description: Gives access to /sq setteamsarea command.
  speepquest.setup.signs:
    default: op
    description: Allows to create and remove signs.
  speepquest.setup.reload:
    default: op
    description: Gives access to /sq reload command.
  sheepquest.setup.help:
    default: op
    description: Gives access to /sq admin command.
  sheepquest.setup.menu:
    default: op
    description: Gives access to setup menu.



  sheepquest.play.*:
    default: true
    description: Gives access to basic plugin commands.
    children:
      sheepquest.play.help: true
      sheepquest.play.join: true
      sheepquest.play.leave: true
      sheepquest.play.quickjoin: true
      sheepquest.play.stats: true
      sheepquest.play.list: true
      sheepquest.play.signs: true
      sheepquest.play.menu: true

  sheepquest.play.help:
    default: true
    description: Gives access to /sq help command.
  sheepquest.play.join:
    default: true
    description: Allows to join arenas.
  sheepquest.play.leave:
    default: true
    description: Allows to leave arenas.
  sheepquest.play.quickjoin:
    default: true
    description:  Gives access to /sq quickjoin command.
  sheepquest.play.stats:
    default: true
    description: Gives access to /sq stats command.
  sheepquest.play.list:
    default: true
    description: Gives access to /sq list command.
  sheepquest.play.signs:
    default: true
    description: Allows to join arenas by signs.
  sheepquest.play.menu:
    default: true
    description: Gives access to arenas menu.



  sheepquest.staff.*:
    default: op
    description: Gives access to moderator plugin commands.
    children:
      sheepquest.staff.start: true
      sheepquest.staff.stop: true
      sheepquest.staff.active: true
      sheepquest.staff.help: true
      sheepquest.staff.menu: true
      sheepquest.staff.kick: true

  sheepquest.staff.help:
    default: true
    description: Gives access to /sq mod command.
  sheepquest.staff.start:
    default: op
    description: Gives access to /sq forcestart command.
  sheepquest.staff.active:
    default: op
    description: Gives access to /sq active command.
  sheepquest.staff.stop:
    default: op
    description: Gives access to /sq forcestop command.
  sheepquest.staff.menu:
    default: op
    description: Gives access to staff menu.
  sheepquest.staff.kick:
    default: op
    description: Gives access to /sq kick command.


  sheepquest.bypass:
    default: op
    description: Allows to bypass blocked commands in arena.
  sheepquest.vip:
    default: op
    description: Allows to join vip arenas.